"""
Page Object Model for example
Auto-generated by Smart Dependency Manager
"""

import logging
from typing import Optional
from playwright.sync_api import Page, Locator, expect

logger = logging.getLogger(__name__)


class ExamplePage:
    """
    Page Object Model for https://example.com
    This is a dynamically generated page object that adapts to any website.
    """
    
    def __init__(self, page: Page):
        """Initialize the page object."""
        self.page = page
        self.url = "https://example.com"
        logger.info(f"Initialized ExamplePage")
    
    def navigate_to(self, url: str = None) -> None:
        """Navigate to the page."""
        target_url = url or self.url
        if target_url:
            logger.info(f"Navigating to {target_url}")
            self.page.goto(target_url)
            self.page.wait_for_load_state("domcontentloaded")
    
    def wait_for_element(self, selector: str, timeout: int = 30000) -> Locator:
        """Wait for an element to be visible."""
        logger.debug(f"Waiting for element: {selector}")
        locator = self.page.locator(selector)
        locator.wait_for(state="visible", timeout=timeout)
        return locator
    
    def click(self, selector: str) -> None:
        """Click an element."""
        logger.debug(f"Clicking element: {selector}")
        self.page.locator(selector).click()
    
    def fill(self, selector: str, value: str) -> None:
        """Fill a form field."""
        logger.debug(f"Filling {selector} with {value}")
        self.page.locator(selector).fill(value)
    
    def get_text(self, selector: str) -> str:
        """Get text from an element."""
        return self.page.locator(selector).text_content() or ""
    
    def is_visible(self, selector: str) -> bool:
        """Check if an element is visible."""
        return self.page.locator(selector).is_visible()
    
    def take_screenshot(self, name: str) -> None:
        """Take a screenshot."""
        path = f"screenshots/{name}.png"
        self.page.screenshot(path=path)
        logger.info(f"Screenshot saved: {path}")
    
    # Generic methods that work for any site
    def find_all_links(self) -> List[str]:
        """Find all links on the page."""
        links = self.page.locator("a[href]").all()
        return [link.get_attribute("href") for link in links]
    
    def find_all_buttons(self) -> List[Locator]:
        """Find all buttons on the page."""
        return self.page.locator("button, input[type='button'], input[type='submit']").all()
    
    def find_all_inputs(self) -> List[Locator]:
        """Find all input fields."""
        return self.page.locator("input, textarea, select").all()
    
    def search_for_text(self, text: str) -> bool:
        """Check if text exists on the page."""
        return self.page.locator(f"text={text}").count() > 0
