version: '3.8'

services:
  cdh-spark:
    build:
      context: .
      dockerfile: Dockerfile.cdh7-spark3
    container_name: cdh7-spark3
    hostname: cdh-spark
    privileged: true
    ports:
      # HDFS ports
      - "9870:9870"   # NameNode Web UI
      - "9864:9864"   # DataNode Web UI
      - "9000:9000"   # HDFS
      # YARN ports
      - "8088:8088"   # ResourceManager Web UI
      - "8042:8042"   # NodeManager Web UI
      # Spark ports
      - "4040:4040"   # Spark Application UI
      - "7077:7077"   # Spark Master
      - "8080:8080"   # Spark Master Web UI
      - "8081:8081"   # Spark Worker Web UI
      - "18080:18080" # Spark History Server
      # Hive ports
      - "10000:10000" # HiveServer2
      - "10002:10002" # HiveServer2 Web UI
      - "9083:9083"   # Hive Metastore
      # Jupyter
      - "8888:8888"   # Jupyter Lab
    volumes:
      - ./workspace:/workspace
      - ./data:/data
      - cdh_hdfs_namenode:/data/hdfs/namenode
      - cdh_hdfs_datanode:/data/hdfs/datanode
      - cdh_hive_warehouse:/user/hive/warehouse
      - cdh_spark_events:/spark-events
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk
      - HADOOP_HOME=/opt/cloudera/parcels/CDH
      - SPARK_HOME=/opt/spark
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
    networks:
      - cdh_network
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 4096
        hard: 4096
    mem_limit: 16g
    cpus: 4

  # Optional: MySQL for Hive Metastore (production setup)
  mysql-metastore:
    image: mysql:5.7
    container_name: cdh-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: metastore
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cdh_network

networks:
  cdh_network:
    driver: bridge

volumes:
  cdh_hdfs_namenode:
  cdh_hdfs_datanode:
  cdh_hive_warehouse:
  cdh_spark_events:
  mysql_data:
  
# Podman specific adjustments
# If using podman-compose, you might need to run:
# sudo sysctl -w vm.max_map_count=262144