#!/usr/bin/env python3
"""
LLM-Optimized Element Extraction Structure for UI Test Generation

This module defines the optimal JSON structure for element extraction that maximizes
the quality of test cases generated by LLMs. Based on research and best practices
for LLM interaction, structured outputs, and UI testing requirements.

The structure is designed to:
1. Provide rich semantic context for LLMs to understand the UI
2. Include hierarchical relationships for understanding page structure
3. Capture interaction patterns and user journeys
4. Enable generation of comprehensive test scenarios
5. Support both functional and non-functional test generation
"""

from typing import List, Dict, Any, Optional, Union, Literal
from datetime import datetime
from enum import Enum
from pydantic import BaseModel, Field, ConfigDict, field_validator
import json


# ============================================================================
# ENHANCED ENUMS FOR BETTER LLM UNDERSTANDING
# ============================================================================

class ElementCategory(str, Enum):
    """High-level element categories that LLMs can reason about"""
    NAVIGATION = "navigation"          # Navigation elements
    FORM_INPUT = "form_input"         # Form inputs and fields
    ACTION = "action"                 # Buttons, links that trigger actions
    CONTENT = "content"               # Static content display
    MEDIA = "media"                   # Images, videos, audio
    FEEDBACK = "feedback"             # Alerts, notifications, messages
    DATA_DISPLAY = "data_display"     # Tables, lists, grids
    INTERACTIVE = "interactive"       # Dropdowns, sliders, toggles
    AUTHENTICATION = "authentication" # Login, signup, password elements
    PAYMENT = "payment"               # Payment-related elements
    SEARCH = "search"                 # Search bars and filters
    SOCIAL = "social"                 # Social media elements

class InteractionPattern(str, Enum):
    """Common interaction patterns for test generation"""
    CLICK = "click"
    TYPE_TEXT = "type_text"
    SELECT_OPTION = "select_option"
    DRAG_DROP = "drag_drop"
    HOVER = "hover"
    SCROLL = "scroll"
    UPLOAD_FILE = "upload_file"
    KEYBOARD_SHORTCUT = "keyboard_shortcut"
    MULTI_STEP = "multi_step"
    VALIDATE = "validate"
    WAIT = "wait"

class TestPriority(str, Enum):
    """Test priority based on element importance"""
    CRITICAL = "critical"     # Core functionality
    HIGH = "high"            # Important features
    MEDIUM = "medium"        # Standard features
    LOW = "low"              # Nice-to-have features
    EXPLORATORY = "exploratory"  # Edge cases

class ValidationRule(str, Enum):
    """Validation rules that can be tested"""
    REQUIRED = "required"
    FORMAT = "format"
    LENGTH = "length"
    RANGE = "range"
    PATTERN = "pattern"
    UNIQUENESS = "uniqueness"
    DEPENDENCY = "dependency"
    BUSINESS_LOGIC = "business_logic"


# ============================================================================
# SEMANTIC CONTEXT FOR LLM UNDERSTANDING
# ============================================================================

class SemanticContext(BaseModel):
    """Rich semantic context to help LLMs understand the element's purpose"""
    
    # Primary purpose
    primary_purpose: str = Field(
        ..., 
        description="Clear description of what this element does"
    )
    
    # Business context
    business_function: Optional[str] = Field(
        None,
        description="Business function this element serves (e.g., 'customer registration', 'payment processing')"
    )
    
    # User intent
    user_intent: Optional[str] = Field(
        None,
        description="What the user is trying to accomplish"
    )
    
    # Related features
    related_features: List[str] = Field(
        default_factory=list,
        description="Related features or functionalities"
    )
    
    # Keywords for search
    keywords: List[str] = Field(
        default_factory=list,
        description="Keywords that describe this element"
    )
    
    # Domain-specific tags
    domain_tags: List[str] = Field(
        default_factory=list,
        description="Domain-specific tags (e.g., 'e-commerce', 'banking', 'healthcare')"
    )


# ============================================================================
# INTERACTION CONTEXT FOR TEST GENERATION
# ============================================================================

class InteractionContext(BaseModel):
    """Context about how users interact with this element"""
    
    # Interaction patterns
    primary_interaction: InteractionPattern = Field(
        ...,
        description="Primary way users interact with this element"
    )
    
    # Alternative interactions
    alternative_interactions: List[InteractionPattern] = Field(
        default_factory=list,
        description="Alternative ways to interact"
    )
    
    # Prerequisites
    prerequisites: List[str] = Field(
        default_factory=list,
        description="What needs to happen before interacting with this element"
    )
    
    # Expected outcomes
    expected_outcomes: List[str] = Field(
        default_factory=list,
        description="What should happen after interaction"
    )
    
    # Common user flows
    common_flows: List[str] = Field(
        default_factory=list,
        description="Common user flows involving this element"
    )
    
    # Error scenarios
    error_scenarios: List[str] = Field(
        default_factory=list,
        description="Common error scenarios to test"
    )
    
    # Timing constraints
    timing_constraints: Optional[Dict[str, Any]] = Field(
        None,
        description="Timing requirements (e.g., timeouts, delays)"
    )


# ============================================================================
# VALIDATION CONTEXT FOR COMPREHENSIVE TESTING
# ============================================================================

class ValidationContext(BaseModel):
    """Validation rules and constraints for testing"""
    
    # Validation rules
    rules: List[ValidationRule] = Field(
        default_factory=list,
        description="Applicable validation rules"
    )
    
    # Specific constraints
    constraints: Dict[str, Any] = Field(
        default_factory=dict,
        description="Specific validation constraints"
    )
    
    # Valid values
    valid_values: List[Any] = Field(
        default_factory=list,
        description="Examples of valid input values"
    )
    
    # Invalid values
    invalid_values: List[Any] = Field(
        default_factory=list,
        description="Examples of invalid input values for negative testing"
    )
    
    # Edge cases
    edge_cases: List[str] = Field(
        default_factory=list,
        description="Edge cases to test"
    )
    
    # Error messages
    error_messages: Dict[str, str] = Field(
        default_factory=dict,
        description="Expected error messages for validation failures"
    )


# ============================================================================
# ACCESSIBILITY CONTEXT FOR INCLUSIVE TESTING
# ============================================================================

class AccessibilityContext(BaseModel):
    """Accessibility information for inclusive test generation"""
    
    # ARIA attributes
    aria_role: Optional[str] = Field(None, description="ARIA role")
    aria_label: Optional[str] = Field(None, description="ARIA label")
    aria_description: Optional[str] = Field(None, description="ARIA description")
    aria_properties: Dict[str, Any] = Field(default_factory=dict, description="Other ARIA properties")
    
    # Keyboard navigation
    keyboard_accessible: bool = Field(True, description="Is keyboard accessible")
    tab_index: Optional[int] = Field(None, description="Tab index")
    keyboard_shortcuts: List[str] = Field(default_factory=list, description="Keyboard shortcuts")
    
    # Screen reader
    screen_reader_text: Optional[str] = Field(None, description="Screen reader text")
    
    # WCAG compliance
    wcag_level: Optional[Literal["A", "AA", "AAA"]] = Field(None, description="WCAG compliance level")
    wcag_issues: List[str] = Field(default_factory=list, description="Known WCAG issues")


# ============================================================================
# HIERARCHICAL CONTEXT FOR PAGE STRUCTURE
# ============================================================================

class HierarchicalContext(BaseModel):
    """Element's position in the page hierarchy"""
    
    # Parent context
    parent_section: Optional[str] = Field(None, description="Parent section/container")
    parent_form: Optional[str] = Field(None, description="Parent form if applicable")
    
    # Sibling elements
    siblings: List[str] = Field(default_factory=list, description="Sibling element identifiers")
    
    # Child elements
    children: List[str] = Field(default_factory=list, description="Child element identifiers")
    
    # Navigation context
    navigation_order: Optional[int] = Field(None, description="Order in navigation flow")
    
    # Group context
    element_group: Optional[str] = Field(None, description="Logical group this element belongs to")
    group_role: Optional[str] = Field(None, description="Role within the group")


# ============================================================================
# VISUAL CONTEXT FOR UI TESTING
# ============================================================================

class VisualContext(BaseModel):
    """Visual properties for UI-specific testing"""
    
    # Position
    x: int = Field(0, description="X coordinate")
    y: int = Field(0, description="Y coordinate")
    width: int = Field(0, description="Width in pixels")
    height: int = Field(0, description="Height in pixels")
    
    # Visibility
    is_visible: bool = Field(True, description="Is currently visible")
    is_above_fold: bool = Field(False, description="Is visible without scrolling")
    z_index: Optional[int] = Field(None, description="Z-index for layering")
    
    # Visual state
    is_highlighted: bool = Field(False, description="Is currently highlighted/focused")
    has_error_styling: bool = Field(False, description="Has error styling applied")
    
    # Responsive behavior
    responsive_behavior: Dict[str, Any] = Field(
        default_factory=dict,
        description="How element behaves at different screen sizes"
    )


# ============================================================================
# STATE CONTEXT FOR DYNAMIC TESTING
# ============================================================================

class StateContext(BaseModel):
    """Element state information for dynamic testing"""
    
    # Current state
    is_enabled: bool = Field(True, description="Is currently enabled")
    is_readonly: bool = Field(False, description="Is read-only")
    is_required: bool = Field(False, description="Is required field")
    is_selected: bool = Field(False, description="Is currently selected")
    is_checked: bool = Field(False, description="Is checked (for checkboxes)")
    
    # State transitions
    possible_states: List[str] = Field(default_factory=list, description="Possible states")
    state_triggers: Dict[str, str] = Field(default_factory=dict, description="What triggers state changes")
    
    # Dynamic behavior
    updates_dynamically: bool = Field(False, description="Updates without page reload")
    update_triggers: List[str] = Field(default_factory=list, description="What triggers updates")
    
    # Dependencies
    depends_on: List[str] = Field(default_factory=list, description="Other elements this depends on")
    affects: List[str] = Field(default_factory=list, description="Other elements this affects")


# ============================================================================
# MAIN LLM-OPTIMIZED ELEMENT STRUCTURE
# ============================================================================

class LLMOptimizedElement(BaseModel):
    """
    Comprehensive element structure optimized for LLM test generation.
    
    This structure provides multiple layers of context to help LLMs:
    1. Understand the element's purpose and business context
    2. Generate meaningful test scenarios
    3. Create comprehensive test coverage
    4. Handle edge cases and error scenarios
    5. Consider accessibility and non-functional requirements
    """
    
    model_config = ConfigDict(extra="allow")
    
    # ========== CORE IDENTIFICATION ==========
    element_id: str = Field(..., description="Unique identifier for this element")
    tag_name: str = Field(..., description="HTML tag name")
    element_category: ElementCategory = Field(..., description="High-level category")
    
    # ========== SELECTORS FOR TEST EXECUTION ==========
    selectors: Dict[str, str] = Field(
        ...,
        description="Multiple selector strategies",
        example={
            "id": "submit-button",
            "css": ".btn.btn-primary",
            "xpath": "//button[@type='submit']",
            "data_testid": "submit-form-button"
        }
    )
    
    # ========== SEMANTIC CONTEXT ==========
    semantic: SemanticContext = Field(
        ...,
        description="Rich semantic context for LLM understanding"
    )
    
    # ========== INTERACTION CONTEXT ==========
    interaction: InteractionContext = Field(
        ...,
        description="How users interact with this element"
    )
    
    # ========== CONTENT ==========
    content: Dict[str, Any] = Field(
        default_factory=dict,
        description="Element content",
        example={
            "text": "Submit Order",
            "placeholder": "Enter email",
            "label": "Email Address",
            "value": "current value",
            "options": ["Option 1", "Option 2"]
        }
    )
    
    # ========== VALIDATION CONTEXT ==========
    validation: Optional[ValidationContext] = Field(
        None,
        description="Validation rules and constraints"
    )
    
    # ========== ACCESSIBILITY CONTEXT ==========
    accessibility: Optional[AccessibilityContext] = Field(
        None,
        description="Accessibility information"
    )
    
    # ========== HIERARCHICAL CONTEXT ==========
    hierarchy: Optional[HierarchicalContext] = Field(
        None,
        description="Position in page hierarchy"
    )
    
    # ========== VISUAL CONTEXT ==========
    visual: Optional[VisualContext] = Field(
        None,
        description="Visual properties"
    )
    
    # ========== STATE CONTEXT ==========
    state: Optional[StateContext] = Field(
        None,
        description="Element state information"
    )
    
    # ========== TEST METADATA ==========
    test_priority: TestPriority = Field(
        TestPriority.MEDIUM,
        description="Priority for test generation"
    )
    
    suggested_test_types: List[str] = Field(
        default_factory=list,
        description="Suggested types of tests for this element",
        example=["functional", "validation", "accessibility", "performance", "security"]
    )
    
    test_data_examples: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Example test data for this element"
    )
    
    # ========== METADATA ==========
    confidence_score: float = Field(
        1.0,
        ge=0.0,
        le=1.0,
        description="Confidence in element extraction"
    )
    
    extraction_timestamp: datetime = Field(
        default_factory=datetime.now,
        description="When element was extracted"
    )
    
    page_context: Dict[str, Any] = Field(
        default_factory=dict,
        description="Page-level context",
        example={
            "url": "https://example.com/checkout",
            "page_title": "Checkout",
            "page_type": "e-commerce_checkout"
        }
    )


# ============================================================================
# PAGE-LEVEL STRUCTURE FOR COMPREHENSIVE TEST GENERATION
# ============================================================================

class PageStructure(BaseModel):
    """Complete page structure for holistic test generation"""
    
    # Page identification
    url: str = Field(..., description="Page URL")
    title: str = Field(..., description="Page title")
    page_type: str = Field(..., description="Type of page (e.g., 'login', 'checkout', 'dashboard')")
    
    # Page metadata
    description: str = Field("", description="Page description for LLM context")
    business_purpose: str = Field("", description="Business purpose of this page")
    
    # Elements organized by category
    elements_by_category: Dict[ElementCategory, List[LLMOptimizedElement]] = Field(
        default_factory=dict,
        description="Elements organized by category"
    )
    
    # User journeys
    user_journeys: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Common user journeys on this page"
    )
    
    # Page-level validations
    page_validations: List[str] = Field(
        default_factory=list,
        description="Page-level validation rules"
    )
    
    # Critical paths
    critical_paths: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Critical user paths that must be tested"
    )
    
    # Performance requirements
    performance_requirements: Dict[str, Any] = Field(
        default_factory=dict,
        description="Performance requirements for the page"
    )
    
    # Security considerations
    security_considerations: List[str] = Field(
        default_factory=list,
        description="Security aspects to test"
    )


# ============================================================================
# LLM PROMPT OPTIMIZATION STRUCTURE
# ============================================================================

class LLMTestGenerationRequest(BaseModel):
    """
    Optimized structure for requesting test generation from LLMs.
    Follows best practices for structured outputs and prompt engineering.
    """
    
    # Context setting
    context: Dict[str, Any] = Field(
        ...,
        description="Context for test generation",
        example={
            "application_type": "e-commerce",
            "testing_framework": "playwright",
            "test_style": "BDD",
            "coverage_goals": ["functional", "edge_cases", "accessibility"]
        }
    )
    
    # Page structure
    page: PageStructure = Field(
        ...,
        description="Complete page structure with elements"
    )
    
    # Specific requirements
    requirements: Dict[str, Any] = Field(
        default_factory=dict,
        description="Specific test requirements",
        example={
            "focus_areas": ["payment_flow", "form_validation"],
            "exclude": ["performance_testing"],
            "max_scenarios": 10,
            "priority": "critical_paths_only"
        }
    )
    
    # Output format specification
    output_format: Dict[str, Any] = Field(
        default_factory=lambda: {
            "format": "gherkin",
            "include_examples": True,
            "include_test_data": True,
            "group_by": "user_journey"
        },
        description="Desired output format"
    )
    
    def to_llm_prompt(self) -> str:
        """Convert to optimized LLM prompt"""
        return f"""
You are an expert QA engineer. Generate comprehensive test cases for the following web page.

CONTEXT:
{json.dumps(self.context, indent=2)}

PAGE STRUCTURE:
{json.dumps(self.page.model_dump(), indent=2)}

REQUIREMENTS:
{json.dumps(self.requirements, indent=2)}

OUTPUT FORMAT:
{json.dumps(self.output_format, indent=2)}

Generate test cases that:
1. Cover all critical user journeys
2. Include positive, negative, and edge cases
3. Consider accessibility requirements
4. Follow the specified output format exactly
5. Use the provided selectors for test implementation

Return ONLY valid JSON matching the specified format.
"""


# ============================================================================
# HELPER FUNCTIONS FOR ELEMENT ENRICHMENT
# ============================================================================

def enrich_element_for_llm(basic_element: Dict[str, Any]) -> LLMOptimizedElement:
    """
    Enrich a basic extracted element with LLM-optimized context.
    This function adds semantic understanding and test-relevant metadata.
    """
    
    # Determine element category based on tag and attributes
    category = determine_element_category(basic_element)
    
    # Build semantic context
    semantic = build_semantic_context(basic_element, category)
    
    # Build interaction context
    interaction = build_interaction_context(basic_element, category)
    
    # Create enriched element
    enriched = LLMOptimizedElement(
        element_id=basic_element.get('element_id', generate_element_id(basic_element)),
        tag_name=basic_element.get('tag_name', 'unknown'),
        element_category=category,
        selectors=extract_selectors(basic_element),
        semantic=semantic,
        interaction=interaction,
        content=extract_content(basic_element),
        validation=build_validation_context(basic_element) if needs_validation(basic_element) else None,
        accessibility=build_accessibility_context(basic_element),
        hierarchy=build_hierarchy_context(basic_element),
        visual=build_visual_context(basic_element),
        state=build_state_context(basic_element),
        test_priority=determine_test_priority(basic_element, category),
        suggested_test_types=suggest_test_types(basic_element, category),
        test_data_examples=generate_test_data_examples(basic_element, category)
    )
    
    return enriched


def determine_element_category(element: Dict[str, Any]) -> ElementCategory:
    """Determine the high-level category of an element"""
    tag = element.get('tag_name', '').lower()
    element_type = element.get('element_type', '').lower()
    role = element.get('role', '').lower()
    
    # Navigation elements
    if tag in ['nav', 'header', 'footer'] or role == 'navigation':
        return ElementCategory.NAVIGATION
    
    # Form inputs
    if tag in ['input', 'textarea', 'select'] or element_type in ['input', 'textarea', 'dropdown']:
        return ElementCategory.FORM_INPUT
    
    # Action elements
    if tag in ['button', 'a'] or element_type == 'button' or role == 'button':
        return ElementCategory.ACTION
    
    # Media elements
    if tag in ['img', 'video', 'audio', 'picture']:
        return ElementCategory.MEDIA
    
    # Data display
    if tag in ['table', 'ul', 'ol', 'dl']:
        return ElementCategory.DATA_DISPLAY
    
    # Default to content
    return ElementCategory.CONTENT


def build_semantic_context(element: Dict[str, Any], category: ElementCategory) -> SemanticContext:
    """Build semantic context for an element"""
    text = element.get('text_content', '')
    aria_label = element.get('aria_label', '')
    
    # Determine purpose based on text and category
    purpose = f"{category.value} element"
    if text:
        purpose = f"{category.value}: {text[:50]}"
    elif aria_label:
        purpose = f"{category.value}: {aria_label}"
    
    return SemanticContext(
        primary_purpose=purpose,
        keywords=extract_keywords(element),
        domain_tags=[]  # Would be enriched based on page context
    )


def build_interaction_context(element: Dict[str, Any], category: ElementCategory) -> InteractionContext:
    """Build interaction context for an element"""
    # Determine primary interaction based on category
    interaction_map = {
        ElementCategory.ACTION: InteractionPattern.CLICK,
        ElementCategory.FORM_INPUT: InteractionPattern.TYPE_TEXT,
        ElementCategory.NAVIGATION: InteractionPattern.CLICK,
        ElementCategory.DATA_DISPLAY: InteractionPattern.VALIDATE,
        ElementCategory.INTERACTIVE: InteractionPattern.SELECT_OPTION
    }
    
    return InteractionContext(
        primary_interaction=interaction_map.get(category, InteractionPattern.CLICK),
        alternative_interactions=[],
        prerequisites=[],
        expected_outcomes=[],
        common_flows=[],
        error_scenarios=[]
    )


def extract_selectors(element: Dict[str, Any]) -> Dict[str, str]:
    """Extract multiple selector strategies"""
    selectors = {}
    
    if element.get('id'):
        selectors['id'] = element['id']
    
    if element.get('css_selector'):
        selectors['css'] = element['css_selector']
    
    if element.get('xpath'):
        selectors['xpath'] = element['xpath']
    
    if element.get('data-testid'):
        selectors['data_testid'] = element['data-testid']
    
    return selectors


def extract_content(element: Dict[str, Any]) -> Dict[str, Any]:
    """Extract element content"""
    content = {}
    
    if element.get('text_content'):
        content['text'] = element['text_content']
    
    if element.get('placeholder'):
        content['placeholder'] = element['placeholder']
    
    if element.get('value'):
        content['value'] = element['value']
    
    if element.get('options'):
        content['options'] = element['options']
    
    return content


def build_validation_context(element: Dict[str, Any]) -> ValidationContext:
    """Build validation context for form elements"""
    rules = []
    
    if element.get('required'):
        rules.append(ValidationRule.REQUIRED)
    
    if element.get('pattern'):
        rules.append(ValidationRule.PATTERN)
    
    if element.get('minlength') or element.get('maxlength'):
        rules.append(ValidationRule.LENGTH)
    
    return ValidationContext(
        rules=rules,
        constraints={},
        valid_values=[],
        invalid_values=[],
        edge_cases=[],
        error_messages={}
    )


def build_accessibility_context(element: Dict[str, Any]) -> AccessibilityContext:
    """Build accessibility context"""
    return AccessibilityContext(
        aria_role=element.get('role'),
        aria_label=element.get('aria_label'),
        aria_description=element.get('aria_describedby'),
        keyboard_accessible=element.get('tab_index', -1) >= 0,
        tab_index=element.get('tab_index'),
        screen_reader_text=element.get('aria_label') or element.get('text_content')
    )


def build_hierarchy_context(element: Dict[str, Any]) -> HierarchicalContext:
    """Build hierarchical context"""
    return HierarchicalContext(
        parent_section=element.get('parent_section'),
        parent_form=element.get('parent_form'),
        siblings=[],
        children=[],
        navigation_order=element.get('tab_index')
    )


def build_visual_context(element: Dict[str, Any]) -> VisualContext:
    """Build visual context"""
    return VisualContext(
        x=element.get('x', 0),
        y=element.get('y', 0),
        width=element.get('width', 0),
        height=element.get('height', 0),
        is_visible=element.get('is_visible', True),
        is_above_fold=element.get('y', 0) < 768  # Approximate fold
    )


def build_state_context(element: Dict[str, Any]) -> StateContext:
    """Build state context"""
    return StateContext(
        is_enabled=element.get('is_enabled', True),
        is_readonly=element.get('readonly', False),
        is_required=element.get('required', False),
        is_selected=element.get('selected', False),
        is_checked=element.get('checked', False),
        possible_states=[],
        state_triggers={},
        updates_dynamically=False,
        update_triggers=[],
        depends_on=[],
        affects=[]
    )


def needs_validation(element: Dict[str, Any]) -> bool:
    """Check if element needs validation context"""
    return element.get('tag_name', '').lower() in ['input', 'textarea', 'select']


def determine_test_priority(element: Dict[str, Any], category: ElementCategory) -> TestPriority:
    """Determine test priority based on element characteristics"""
    # Critical elements
    if category in [ElementCategory.AUTHENTICATION, ElementCategory.PAYMENT]:
        return TestPriority.CRITICAL
    
    # High priority elements
    if category in [ElementCategory.ACTION, ElementCategory.FORM_INPUT]:
        return TestPriority.HIGH
    
    # Default to medium
    return TestPriority.MEDIUM


def suggest_test_types(element: Dict[str, Any], category: ElementCategory) -> List[str]:
    """Suggest appropriate test types for an element"""
    test_types = ["functional"]
    
    if category == ElementCategory.FORM_INPUT:
        test_types.extend(["validation", "boundary"])
    
    if element.get('aria_label') or element.get('role'):
        test_types.append("accessibility")
    
    if category in [ElementCategory.AUTHENTICATION, ElementCategory.PAYMENT]:
        test_types.append("security")
    
    return test_types


def generate_test_data_examples(element: Dict[str, Any], category: ElementCategory) -> List[Dict[str, Any]]:
    """Generate example test data for an element"""
    examples = []
    
    if category == ElementCategory.FORM_INPUT:
        input_type = element.get('input_type', 'text')
        
        if input_type == 'email':
            examples.extend([
                {"value": "test@example.com", "expected": "valid"},
                {"value": "invalid-email", "expected": "invalid"},
                {"value": "", "expected": "required_error"}
            ])
        elif input_type == 'number':
            examples.extend([
                {"value": "123", "expected": "valid"},
                {"value": "abc", "expected": "invalid"},
                {"value": "-1", "expected": "range_error"}
            ])
    
    return examples


def extract_keywords(element: Dict[str, Any]) -> List[str]:
    """Extract keywords from element for semantic understanding"""
    keywords = []
    
    # Extract from text content
    if element.get('text_content'):
        words = element['text_content'].lower().split()
        keywords.extend([w for w in words if len(w) > 3][:5])
    
    # Extract from aria-label
    if element.get('aria_label'):
        words = element['aria_label'].lower().split()
        keywords.extend([w for w in words if len(w) > 3][:3])
    
    return list(set(keywords))


def generate_element_id(element: Dict[str, Any]) -> str:
    """Generate unique element ID"""
    import hashlib
    
    # Create ID from element properties
    id_source = f"{element.get('tag_name', '')}_{element.get('xpath', '')}_{element.get('text_content', '')}"
    return hashlib.md5(id_source.encode()).hexdigest()[:8]


# ============================================================================
# EXAMPLE USAGE
# ============================================================================

if __name__ == "__main__":
    # Example of enriching a basic element
    basic_element = {
        "tag_name": "button",
        "element_type": "button",
        "text_content": "Submit Order",
        "id": "submit-btn",
        "css_selector": "#submit-btn",
        "xpath": "//button[@id='submit-btn']",
        "is_visible": True,
        "is_enabled": True,
        "aria_label": "Submit your order"
    }
    
    # Enrich for LLM
    enriched = enrich_element_for_llm(basic_element)
    
    # Convert to JSON for LLM
    print(json.dumps(enriched.model_dump(), indent=2, default=str))
    
    # Example of creating a test generation request
    page = PageStructure(
        url="https://example.com/checkout",
        title="Checkout",
        page_type="e-commerce_checkout",
        description="Checkout page for completing purchase",
        business_purpose="Allow customers to complete their purchase"
    )
    
    request = LLMTestGenerationRequest(
        context={
            "application_type": "e-commerce",
            "testing_framework": "playwright",
            "test_style": "BDD"
        },
        page=page,
        requirements={
            "focus_areas": ["payment_validation", "form_submission"],
            "max_scenarios": 5
        }
    )
    
    # Generate LLM prompt
    print("\n" + "="*50)
    print("LLM PROMPT:")
    print("="*50)
    print(request.to_llm_prompt())