"""
Pytest configuration and fixtures.
Generated by Advanced Test Code Generator
"""

import pytest
from playwright.sync_api import sync_playwright, Browser, BrowserContext, Page
from typing import Generator
import os
import logging
from pathlib import Path
from datetime import datetime

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


@pytest.fixture(scope="session")
def browser() -> Generator[Browser, None, None]:
    """
    Create browser instance for test session.
    
    Yields:
        Browser instance
    """
    with sync_playwright() as playwright:
        # Browser configuration
        headless = os.getenv('HEADLESS', 'true').lower() == 'true'
        slow_mo = int(os.getenv('SLOW_MO', '0'))
        
        # Launch browser
        browser = playwright.chromium.launch(
            headless=headless,
            slow_mo=slow_mo,
            args=['--disable-blink-features=AutomationControlled']
        )
        
        yield browser
        
        browser.close()


@pytest.fixture(scope="function")
def context(browser: Browser) -> Generator[BrowserContext, None, None]:
    """
    Create browser context for each test.
    
    Args:
        browser: Browser instance
        
    Yields:
        Browser context
    """
    # Context options
    context_options = {
        'viewport': {'width': 1920, 'height': 1080},
        'ignore_https_errors': True,
        'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    }
    
    # Add video recording if enabled
    if os.getenv('RECORD_VIDEO', 'false').lower() == 'true':
        video_dir = Path('videos')
        video_dir.mkdir(exist_ok=True)
        context_options['record_video_dir'] = str(video_dir)
    
    # Create context
    context = browser.new_context(**context_options)
    
    # Add request/response logging if debug mode
    if os.getenv('DEBUG', 'false').lower() == 'true':
        context.on("request", lambda request: logger.debug(f"Request: {request.url}"))
        context.on("response", lambda response: logger.debug(f"Response: {response.url} - {response.status}"))
    
    yield context
    
    context.close()


@pytest.fixture(scope="function")
def page(context: BrowserContext) -> Generator[Page, None, None]:
    """
    Create page for each test.
    
    Args:
        context: Browser context
        
    Yields:
        Page instance
    """
    page = context.new_page()
    
    # Set default timeout
    timeout = int(os.getenv('DEFAULT_TIMEOUT', '30000'))
    page.set_default_timeout(timeout)
    
    yield page
    
    page.close()


@pytest.fixture(scope="session", autouse=True)
def setup_test_environment():
    """Setup test environment before running tests."""
    # Create necessary directories
    directories = ['screenshots', 'videos', 'logs', 'reports']
    for directory in directories:
        Path(directory).mkdir(exist_ok=True)
    
    logger.info("Test environment setup complete")
    
    yield
    
    logger.info("Test session complete")


def pytest_configure(config):
    """Configure pytest with custom markers."""
    config.addinivalue_line("markers", "critical: Critical test cases")
    config.addinivalue_line("markers", "high: High priority test cases")
    config.addinivalue_line("markers", "medium: Medium priority test cases")
    config.addinivalue_line("markers", "low: Low priority test cases")
    config.addinivalue_line("markers", "smoke: Smoke test cases")
    config.addinivalue_line("markers", "regression: Regression test cases")


def pytest_html_report_title(report):
    """Set custom report title."""
    report.title = "Test Automation Report - Generated Tests"
