
"""
Base Page Object Model class for all pages.
Generated by Advanced Test Code Generator
"""

from playwright.sync_api import Page, expect, TimeoutError
from typing import Optional, Any
import logging
import os
from datetime import datetime


class BasePage:
    """Base class for all page objects."""
    
    def __init__(self, page: Page):
        """
        Initialize base page.
        
        Args:
            page: Playwright page instance
        """
        self.page = page
        self.logger = logging.getLogger(self.__class__.__name__)
        self.timeout = int(os.getenv('DEFAULT_TIMEOUT', '30000'))
        
    def navigate_to(self, url: str) -> None:
        """
        Navigate to specified URL.
        
        Args:
            url: URL to navigate to
        """
        self.logger.info(f"Navigating to: {url}")
        self.page.goto(url, wait_until="domcontentloaded")
        
    def wait_for_element(self, selector: str, state: str = "visible", timeout: Optional[int] = None) -> None:
        """
        Wait for element to be in specified state.
        
        Args:
            selector: Element selector
            state: Expected state (visible, hidden, attached, detached)
            timeout: Custom timeout in milliseconds
        """
        timeout = timeout or self.timeout
        self.logger.debug(f"Waiting for element: {selector} to be {state}")
        self.page.locator(selector).wait_for(state=state, timeout=timeout)
    
    def click_with_retry(self, selector: str, retries: int = 3) -> bool:
        """
        Click element with retry logic.
        
        Args:
            selector: Element selector
            retries: Number of retry attempts
            
        Returns:
            True if click successful, False otherwise
        """
        for attempt in range(retries):
            try:
                element = self.page.locator(selector)
                element.wait_for(state="visible", timeout=self.timeout)
                element.click()
                self.logger.debug(f"Successfully clicked: {selector}")
                return True
            except TimeoutError:
                self.logger.warning(f"Attempt {attempt + 1} failed for selector: {selector}")
                if attempt == retries - 1:
                    self.take_screenshot(f"click_failed_{selector}")
                    raise
        return False
    
    def fill_field(self, selector: str, value: str, clear_first: bool = True) -> None:
        """
        Fill input field with value.
        
        Args:
            selector: Input field selector
            value: Value to fill
            clear_first: Whether to clear field first
        """
        element = self.page.locator(selector)
        element.wait_for(state="visible", timeout=self.timeout)
        if clear_first:
            element.clear()
        element.fill(value)
        self.logger.debug(f"Filled {selector} with value")
    
    def get_text(self, selector: str) -> str:
        """
        Get text content of element.
        
        Args:
            selector: Element selector
            
        Returns:
            Text content of element
        """
        element = self.page.locator(selector)
        element.wait_for(state="visible", timeout=self.timeout)
        return element.text_content() or ""
    
    def is_element_visible(self, selector: str, timeout: Optional[int] = None) -> bool:
        """
        Check if element is visible.
        
        Args:
            selector: Element selector
            timeout: Custom timeout
            
        Returns:
            True if element is visible, False otherwise
        """
        try:
            timeout = timeout or 5000  # Shorter timeout for visibility checks
            self.page.locator(selector).wait_for(state="visible", timeout=timeout)
            return True
        except TimeoutError:
            return False
    
    def take_screenshot(self, name: str = None) -> str:
        """
        Take screenshot of current page.
        
        Args:
            name: Screenshot name (optional)
            
        Returns:
            Path to screenshot file
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        name = name or "screenshot"
        screenshot_dir = Path("screenshots")
        screenshot_dir.mkdir(exist_ok=True)
        
        filepath = screenshot_dir / f"{timestamp}_{name}.png"
        self.page.screenshot(path=str(filepath))
        self.logger.info(f"Screenshot saved: {filepath}")
        return str(filepath)
    
    def wait_for_load_state(self, state: str = "networkidle") -> None:
        """
        Wait for page load state.
        
        Args:
            state: Load state to wait for
        """
        self.page.wait_for_load_state(state)
    
    def get_current_url(self) -> str:
        """
        Get current page URL.
        
        Returns:
            Current URL
        """
        return self.page.url
    
    def handle_dialog(self, accept: bool = True, prompt_text: str = "") -> None:
        """
        Handle JavaScript dialogs (alert, confirm, prompt).
        
        Args:
            accept: Whether to accept or dismiss dialog
            prompt_text: Text to enter in prompt dialog
        """
        def dialog_handler(dialog):
            if accept:
                dialog.accept(prompt_text)
            else:
                dialog.dismiss()
        
        self.page.on("dialog", dialog_handler)
