
"""
GitHub Homepage Page Object Model.
Generated by Advanced Test Code Generator
"""

from playwright.sync_api import Page, expect
from .base_page import BasePage
from typing import Optional
import os


class GitHubHomePage(BasePage):
    """Page object for GitHub homepage."""
    
    def __init__(self, page: Page):
        """
        Initialize GitHub homepage.
        
        Args:
            page: Playwright page instance
        """
        super().__init__(page)
        
        # Define locators
        self.hero_email_input = page.locator("#hero_user_email")
        self.hero_signup_button = page.locator("button[data-testid='hero-signup-button']")
        self.sign_in_link = page.locator("a[href='/login']")
        self.search_button = page.locator("button[aria-label='Search']")
        self.navigation_menu = page.locator("nav[aria-label='Global']")
        
        # Alternative selectors for resilience
        self.hero_email_alternatives = [
            "#hero_user_email",
            "input[placeholder*='email']",
            "//input[@id='hero_user_email']"
        ]
        
    def enter_hero_email(self, email: str) -> None:
        """
        Enter email in hero section.
        
        Args:
            email: Email address to enter
        """
        self.logger.info(f"Entering email in hero section")
        # Try multiple selectors for resilience
        for selector in self.hero_email_alternatives:
            if self.is_element_visible(selector, timeout=2000):
                self.fill_field(selector, email)
                return
        raise Exception("Could not find hero email input")
    
    def click_hero_signup(self) -> None:
        """Click the hero section signup button."""
        self.logger.info("Clicking hero signup button")
        self.click_with_retry(self.hero_signup_button)
    
    def sign_up_with_email(self, email: str) -> None:
        """
        Complete signup process with email.
        
        Args:
            email: Email address for signup
        """
        self.enter_hero_email(email)
        self.click_hero_signup()
        # Wait for navigation
        self.wait_for_load_state("networkidle")
    
    def navigate_to_login(self) -> None:
        """Navigate to login page."""
        self.logger.info("Navigating to login page")
        self.sign_in_link.click()
        expect(self.page).to_have_url("**/login")
    
    def search(self, query: str) -> None:
        """
        Perform search.
        
        Args:
            query: Search query
        """
        self.logger.info(f"Searching for: {query}")
        self.search_button.click()
        search_input = self.page.locator("input[name='q']")
        search_input.fill(query)
        search_input.press("Enter")
    
    def is_homepage_loaded(self) -> bool:
        """
        Check if homepage is loaded.
        
        Returns:
            True if homepage is loaded
        """
        return self.is_element_visible(self.hero_email_input) or                self.is_element_visible(self.navigation_menu)
