#!/usr/bin/env python3
"""
Initialize components in the database
This script populates the database with all necessary components
"""

from pathlib import Path
from decimal import Decimal
from core import InfrastructureAuditSystem, AuditSystemConfig
from models import Component, CostType, Layer, Category
import json


def create_categories(system):
    """Create component categories"""
    categories = [
        {"code": "runtime", "name": "Runtime Environments", "layer_id": 2},  # runtime layer
        {"code": "tools", "name": "Development Tools", "layer_id": 3},  # development layer
        {"code": "vcs", "name": "Version Control", "layer_id": 3},  # development layer
        {"code": "ai_llm", "name": "AI/LLM", "layer_id": 5},  # ai_ml layer
        {"code": "database", "name": "Databases", "layer_id": 4},  # database layer
        {"code": "backend", "name": "Backend", "layer_id": 6},  # backend layer
        {"code": "frontend", "name": "Frontend", "layer_id": 6},  # backend layer (web)
        {"code": "testing", "name": "Testing", "layer_id": 3},  # development layer
        {"code": "container", "name": "Containers", "layer_id": 1},  # hardware layer
        {"code": "monitoring", "name": "Monitoring", "layer_id": 7},  # automation layer
        {"code": "security", "name": "Security", "layer_id": 7},  # automation layer
        {"code": "automation", "name": "Automation", "layer_id": 7},  # automation layer
    ]

    with system.db_manager.get_connection() as conn:
        for cat in categories:
            conn.execute("""
                INSERT OR IGNORE INTO categories (code, name, layer_id)
                VALUES (?, ?, ?)
            """, (cat["code"], cat["name"], cat["layer_id"]))
        conn.commit()


def create_components(system):
    """Create all infrastructure components"""
    components = [
        # Runtime environments
        Component(
            code="python_3.13",
            name="Python 3.13",
            category_id=1,
            layer_id=1,
            description="Latest Python runtime",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="nodejs_22_lts",
            name="Node.js 22 LTS",
            category_id=1,
            layer_id=1,
            description="Node.js JavaScript runtime",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),

        # Package managers
        Component(
            code="uv_package_manager",
            name="uv Package Manager",
            category_id=2,
            layer_id=2,
            description="Fast Python package manager",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="pnpm",
            name="pnpm",
            category_id=2,
            layer_id=2,
            description="Fast, disk space efficient package manager",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),

        # Development tools
        Component(
            code="vscode",
            name="VS Code",
            category_id=2,
            layer_id=2,
            description="Visual Studio Code editor",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="vscode_extensions",
            name="VS Code Extensions",
            category_id=2,
            layer_id=2,
            description="Essential VS Code extensions",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="vscodium",
            name="VSCodium",
            category_id=2,
            layer_id=2,
            description="Free/Libre Open Source Software Binaries of VSCode",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),

        # Version control
        Component(
            code="git",
            name="Git",
            category_id=3,
            layer_id=2,
            description="Distributed version control",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="github_cli",
            name="GitHub CLI",
            category_id=3,
            layer_id=2,
            description="GitHub command line tool",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="lazygit",
            name="LazyGit",
            category_id=3,
            layer_id=2,
            description="Simple terminal UI for git commands",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),

        # AI/LLM services
        Component(
            code="gemini_api",
            name="Google Gemini API",
            category_id=4,
            layer_id=5,
            description="Google Gemini language model API",
            is_ai_component=True,
            cost_type=CostType.USAGE_BASED,
            estimated_monthly_cost_min=Decimal("10.00"),
            estimated_monthly_cost_max=Decimal("100.00"),
            metadata={"models": ["gemini-2.5-flash"], "free_tier": True}
        ),
        Component(
            code="ollama",
            name="Ollama",
            category_id=4,
            layer_id=4,
            description="Local large language model runner",
            is_ai_component=True,
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="localai",
            name="LocalAI",
            category_id=4,
            layer_id=4,
            description="OpenAI compatible local AI",
            is_ai_component=True,
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="openai_api",
            name="OpenAI API",
            category_id=4,
            layer_id=4,
            description="OpenAI GPT API",
            is_ai_component=True,
            cost_type=CostType.USAGE_BASED,
            estimated_monthly_cost_min=Decimal("20"),
            estimated_monthly_cost_max=Decimal("500"),
        ),
        Component(
            code="anthropic_api",
            name="Anthropic Claude API",
            category_id=4,
            layer_id=4,
            description="Anthropic Claude API",
            is_ai_component=True,
            cost_type=CostType.USAGE_BASED,
            estimated_monthly_cost_min=Decimal("20"),
            estimated_monthly_cost_max=Decimal("500"),
        ),
        Component(
            code="groq_api",
            name="Groq API",
            category_id=4,
            layer_id=4,
            description="Groq fast inference API",
            is_ai_component=True,
            cost_type=CostType.USAGE_BASED,
            estimated_monthly_cost_min=Decimal("10"),
            estimated_monthly_cost_max=Decimal("100"),
        ),

        # AI frameworks
        Component(
            code="langchain",
            name="LangChain",
            category_id=4,
            layer_id=4,
            description="Framework for LLM applications",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="langchain_core",
            name="LangChain Core",
            category_id=4,
            layer_id=4,
            description="Core LangChain components",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="langchain_community",
            name="LangChain Community",
            category_id=4,
            layer_id=4,
            description="Community LangChain integrations",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="langgraph",
            name="LangGraph",
            category_id=4,
            layer_id=4,
            description="LangChain graph framework",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="llamaindex",
            name="LlamaIndex",
            category_id=4,
            layer_id=4,
            description="Data framework for LLM applications",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="huggingface_transformers",
            name="HuggingFace Transformers",
            category_id=4,
            layer_id=4,
            description="State-of-the-art ML models",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="mcp_sdk",
            name="MCP SDK",
            category_id=4,
            layer_id=4,
            description="Model Context Protocol SDK",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),

        # Databases
        Component(
            code="sqlite3",
            name="SQLite3",
            category_id=5,
            layer_id=3,
            description="Embedded SQL database",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="postgresql",
            name="PostgreSQL",
            category_id=5,
            layer_id=3,
            description="PostgreSQL database",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="postgresql_17",
            name="PostgreSQL 17",
            category_id=5,
            layer_id=3,
            description="Latest PostgreSQL version",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="redis",
            name="Redis",
            category_id=5,
            layer_id=3,
            description="In-memory data structure store",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="falkordb",
            name="FalkorDB",
            category_id=5,
            layer_id=3,
            description="Graph database",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="qdrant",
            name="Qdrant",
            category_id=5,
            layer_id=3,
            description="Vector database",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="meilisearch",
            name="MeiliSearch",
            category_id=5,
            layer_id=3,
            description="Search engine",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="mongodb_community",
            name="MongoDB Community",
            category_id=5,
            layer_id=3,
            description="NoSQL document database",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),

        # Backend frameworks
        Component(
            code="fastapi",
            name="FastAPI",
            category_id=6,
            layer_id=5,
            description="Modern Python web API framework",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="django",
            name="Django",
            category_id=6,
            layer_id=5,
            description="Python web framework",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="pydantic_v2",
            name="Pydantic v2",
            category_id=6,
            layer_id=5,
            description="Data validation using Python type annotations",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="sqlalchemy_2",
            name="SQLAlchemy 2.0",
            category_id=6,
            layer_id=5,
            description="SQL toolkit and ORM",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="alembic",
            name="Alembic",
            category_id=6,
            layer_id=5,
            description="Database migration tool",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),

        # Frontend frameworks
        Component(
            code="react",
            name="React",
            category_id=7,
            layer_id=6,
            description="React JavaScript library",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="react_19",
            name="React 19",
            category_id=7,
            layer_id=6,
            description="Latest React version",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="vue_3",
            name="Vue.js 3",
            category_id=7,
            layer_id=6,
            description="Progressive JavaScript framework",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="typescript",
            name="TypeScript",
            category_id=7,
            layer_id=6,
            description="Typed superset of JavaScript",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="tailwind_css_4",
            name="Tailwind CSS 4",
            category_id=7,
            layer_id=6,
            description="Utility-first CSS framework",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="vite",
            name="Vite",
            category_id=7,
            layer_id=6,
            description="Fast frontend build tool",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="html5_css3_vanilla",
            name="HTML5/CSS3 Vanilla",
            category_id=7,
            layer_id=6,
            description="Plain HTML5 and CSS3",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),

        # Testing
        Component(
            code="pytest",
            name="pytest",
            category_id=8,
            layer_id=2,
            description="Python testing framework",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="playwright",
            name="Playwright",
            category_id=8,
            layer_id=2,
            description="Browser automation framework",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="ruff",
            name="Ruff",
            category_id=8,
            layer_id=2,
            description="Fast Python linter",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="mypy",
            name="mypy",
            category_id=8,
            layer_id=2,
            description="Static type checker for Python",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),

        # Containers
        Component(
            code="docker",
            name="Docker",
            category_id=9,
            layer_id=0,
            description="Container platform",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="podman",
            name="Podman",
            category_id=9,
            layer_id=0,
            description="Daemonless container engine",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="podman_compose",
            name="Podman Compose",
            category_id=9,
            layer_id=0,
            description="Podman compose orchestration",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="kubernetes",
            name="Kubernetes",
            category_id=9,
            layer_id=0,
            description="Container orchestration",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="kubernetes_k3s",
            name="K3s",
            category_id=9,
            layer_id=0,
            description="Lightweight Kubernetes",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),

        # Monitoring
        Component(
            code="prometheus",
            name="Prometheus",
            category_id=10,
            layer_id=6,
            description="Monitoring system and time series database",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="grafana",
            name="Grafana",
            category_id=10,
            layer_id=6,
            description="Analytics and monitoring platform",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="opentelemetry",
            name="OpenTelemetry",
            category_id=10,
            layer_id=6,
            description="Observability framework",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="jaeger",
            name="Jaeger",
            category_id=10,
            layer_id=6,
            description="Distributed tracing system",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),

        # Security
        Component(
            code="hashicorp_vault",
            name="HashiCorp Vault",
            category_id=11,
            layer_id=6,
            description="Secrets management",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="keycloak",
            name="Keycloak",
            category_id=11,
            layer_id=6,
            description="Identity and access management",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),

        # Automation
        Component(
            code="n8n_selfhosted",
            name="n8n (Self-hosted)",
            category_id=12,
            layer_id=6,
            description="Workflow automation platform",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="apache_airflow",
            name="Apache Airflow",
            category_id=12,
            layer_id=6,
            description="Workflow orchestration platform",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),

        # Cloud services (for hybrid/enterprise)
        Component(
            code="aws_services",
            name="AWS Services",
            category_id=2,
            layer_id=0,
            description="Amazon Web Services",
            is_opensource=False,
            cost_type=CostType.USAGE_BASED,
            estimated_monthly_cost_min=Decimal("100"),
            estimated_monthly_cost_max=Decimal("5000"),
        ),
        Component(
            code="gcp_services",
            name="GCP Services",
            category_id=2,
            layer_id=0,
            description="Google Cloud Platform",
            is_opensource=False,
            cost_type=CostType.USAGE_BASED,
            estimated_monthly_cost_min=Decimal("100"),
            estimated_monthly_cost_max=Decimal("5000"),
        ),
        Component(
            code="azure_services",
            name="Azure Services",
            category_id=2,
            layer_id=0,
            description="Microsoft Azure",
            is_opensource=False,
            cost_type=CostType.USAGE_BASED,
            estimated_monthly_cost_min=Decimal("100"),
            estimated_monthly_cost_max=Decimal("5000"),
        ),
        Component(
            code="vercel",
            name="Vercel",
            category_id=2,
            layer_id=6,
            description="Frontend deployment platform",
            is_opensource=False,
            cost_type=CostType.FREEMIUM,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("20"),
        ),
        Component(
            code="supabase",
            name="Supabase",
            category_id=5,
            layer_id=3,
            description="Open source Firebase alternative",
            is_opensource=True,
            cost_type=CostType.FREEMIUM,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("25"),
        ),
        Component(
            code="railway",
            name="Railway",
            category_id=2,
            layer_id=0,
            description="Infrastructure deployment platform",
            is_opensource=False,
            cost_type=CostType.USAGE_BASED,
            estimated_monthly_cost_min=Decimal("5"),
            estimated_monthly_cost_max=Decimal("50"),
        ),
        Component(
            code="sentry_free",
            name="Sentry (Free Tier)",
            category_id=10,
            layer_id=6,
            description="Error tracking and monitoring",
            is_opensource=False,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="posthog",
            name="PostHog",
            category_id=10,
            layer_id=6,
            description="Product analytics",
            is_opensource=True,
            cost_type=CostType.FREEMIUM,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("50"),
        ),

        # Additional tools for profiles
        Component(
            code="rust",
            name="Rust",
            category_id=1,
            layer_id=1,
            description="Rust programming language",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="parent_profile",
            name="Parent Profile Components",
            category_id=2,
            layer_id=2,
            description="Components inherited from parent profile",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),

        # Enterprise-specific components
        Component(
            code="github_enterprise",
            name="GitHub Enterprise",
            category_id=3,
            layer_id=2,
            description="GitHub Enterprise version control",
            is_opensource=False,
            cost_type=CostType.USAGE_BASED,
            estimated_monthly_cost_min=Decimal("21"),
            estimated_monthly_cost_max=Decimal("21"),
        ),
        Component(
            code="gitlab_ee",
            name="GitLab Enterprise Edition",
            category_id=3,
            layer_id=2,
            description="GitLab Enterprise version control",
            is_opensource=False,
            cost_type=CostType.USAGE_BASED,
            estimated_monthly_cost_min=Decimal("29"),
            estimated_monthly_cost_max=Decimal("29"),
        ),
        Component(
            code="kong_enterprise",
            name="Kong Enterprise",
            category_id=6,
            layer_id=5,
            description="API Gateway",
            is_opensource=False,
            cost_type=CostType.ENTERPRISE,
            estimated_monthly_cost_min=Decimal("500"),
            estimated_monthly_cost_max=Decimal("2000"),
        ),
        Component(
            code="nginx_plus",
            name="NGINX Plus",
            category_id=6,
            layer_id=5,
            description="Commercial NGINX",
            is_opensource=False,
            cost_type=CostType.ENTERPRISE,
            estimated_monthly_cost_min=Decimal("250"),
            estimated_monthly_cost_max=Decimal("1000"),
        ),
        Component(
            code="cloudflare_enterprise",
            name="Cloudflare Enterprise",
            category_id=2,
            layer_id=0,
            description="Enterprise CDN and security",
            is_opensource=False,
            cost_type=CostType.ENTERPRISE,
            estimated_monthly_cost_min=Decimal("5000"),
            estimated_monthly_cost_max=Decimal("20000"),
        ),
        Component(
            code="fastly",
            name="Fastly",
            category_id=2,
            layer_id=0,
            description="Edge cloud platform",
            is_opensource=False,
            cost_type=CostType.USAGE_BASED,
            estimated_monthly_cost_min=Decimal("50"),
            estimated_monthly_cost_max=Decimal("5000"),
        ),
        Component(
            code="datadog",
            name="Datadog",
            category_id=10,
            layer_id=6,
            description="Monitoring and analytics platform",
            is_opensource=False,
            cost_type=CostType.USAGE_BASED,
            estimated_monthly_cost_min=Decimal("15"),
            estimated_monthly_cost_max=Decimal("50"),
        ),
        Component(
            code="new_relic",
            name="New Relic",
            category_id=10,
            layer_id=6,
            description="Application performance monitoring",
            is_opensource=False,
            cost_type=CostType.USAGE_BASED,
            estimated_monthly_cost_min=Decimal("25"),
            estimated_monthly_cost_max=Decimal("100"),
        ),
        Component(
            code="grafana_enterprise",
            name="Grafana Enterprise",
            category_id=10,
            layer_id=6,
            description="Commercial Grafana",
            is_opensource=False,
            cost_type=CostType.ENTERPRISE,
            estimated_monthly_cost_min=Decimal("100"),
            estimated_monthly_cost_max=Decimal("500"),
        ),
        Component(
            code="hashicorp_vault_enterprise",
            name="HashiCorp Vault Enterprise",
            category_id=11,
            layer_id=6,
            description="Enterprise secrets management",
            is_opensource=False,
            cost_type=CostType.ENTERPRISE,
            estimated_monthly_cost_min=Decimal("500"),
            estimated_monthly_cost_max=Decimal("2000"),
        ),
        Component(
            code="okta",
            name="Okta",
            category_id=11,
            layer_id=6,
            description="Enterprise identity provider",
            is_opensource=False,
            cost_type=CostType.USAGE_BASED,
            estimated_monthly_cost_min=Decimal("3"),
            estimated_monthly_cost_max=Decimal("15"),
        ),
        Component(
            code="auth0",
            name="Auth0",
            category_id=11,
            layer_id=6,
            description="Authentication platform",
            is_opensource=False,
            cost_type=CostType.FREEMIUM,
            estimated_monthly_cost_min=Decimal("23"),
            estimated_monthly_cost_max=Decimal("500"),
        ),
        Component(
            code="cloudflare_waf",
            name="Cloudflare WAF",
            category_id=11,
            layer_id=6,
            description="Web application firewall",
            is_opensource=False,
            cost_type=CostType.FREEMIUM,
            estimated_monthly_cost_min=Decimal("20"),
            estimated_monthly_cost_max=Decimal("200"),
        ),
        Component(
            code="veracode",
            name="Veracode",
            category_id=11,
            layer_id=6,
            description="Application security platform",
            is_opensource=False,
            cost_type=CostType.ENTERPRISE,
            estimated_monthly_cost_min=Decimal("1000"),
            estimated_monthly_cost_max=Decimal("5000"),
        ),
        Component(
            code="velero",
            name="Velero",
            category_id=9,
            layer_id=0,
            description="Kubernetes backup and recovery",
            is_opensource=True,
            cost_type=CostType.FREE,
            estimated_monthly_cost_min=Decimal("0"),
            estimated_monthly_cost_max=Decimal("0"),
        ),
        Component(
            code="aws_backup",
            name="AWS Backup",
            category_id=2,
            layer_id=0,
            description="Centralized backup across AWS services",
            is_opensource=False,
            cost_type=CostType.USAGE_BASED,
            estimated_monthly_cost_min=Decimal("10"),
            estimated_monthly_cost_max=Decimal("500"),
        ),
        Component(
            code="veeam",
            name="Veeam",
            category_id=2,
            layer_id=0,
            description="Enterprise backup solution",
            is_opensource=False,
            cost_type=CostType.ENTERPRISE,
            estimated_monthly_cost_min=Decimal("500"),
            estimated_monthly_cost_max=Decimal("3000"),
        ),
    ]

    # Register all components
    for component in components:
        try:
            system.register_component(component)
            print(f"Registered: {component.code}")
        except Exception as e:
            print(f"Failed to register {component.code}: {e}")


def main():
    """Main initialization function"""
    print("Initializing Infrastructure Audit System Components...")

    # Create system with default config
    config = AuditSystemConfig()
    system = InfrastructureAuditSystem(config)

    print("Creating categories...")
    create_categories(system)

    print("Creating components...")
    create_components(system)

    # Get statistics
    stats = system.get_system_stats()
    print(f"\nInitialization complete!")
    print(f"Total components: {sum(stats.get('components', {}).values())}")
    print(f"Component types: {stats.get('components', {})}")


if __name__ == "__main__":
    main()