"""
Test suite for critical_path strategy.
Generated by Advanced Test Code Generator
URL: https://github.com
"""

import pytest
from playwright.sync_api import Page, expect
import os
import logging
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv
import sys

# Add parent directory to path for imports
sys.path.append(str(Path(__file__).parent.parent))

# Import page objects
from pages.github_homepage import GitHubHomePage
from pages.base_page import BasePage

# Load environment variables
load_dotenv('.env.test')

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class TestCriticalPath:
    """Test class for critical_path scenarios."""
    
    @pytest.fixture(autouse=True)
    def setup(self, page: Page):
        """
        Setup test environment.
        
        Args:
            page: Playwright page fixture
        """
        self.page = page
        self.base_url = os.getenv('BASE_URL', 'https://github.com')
        self.timeout = int(os.getenv('DEFAULT_TIMEOUT', '30000'))
        
        # Navigate to base URL
        self.page.goto(self.base_url)
        self.page.wait_for_load_state("networkidle")
        
        yield
        
        # Cleanup
        if hasattr(self, 'screenshot_on_failure') and self.screenshot_on_failure:
            self._take_failure_screenshot()
    
    def _take_failure_screenshot(self):
        """Take screenshot on test failure."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        screenshot_dir = Path("screenshots/failures")
        screenshot_dir.mkdir(parents=True, exist_ok=True)
        
        screenshot_path = screenshot_dir / f"{timestamp}_critical_path_failure.png"
        self.page.screenshot(path=str(screenshot_path))
        logger.info(f"Failure screenshot saved: {screenshot_path}")

    
    @pytest.mark.critical
    def test_verify_successful_user_sign_up_via_hero_section_wi(self):
        """
        Verify successful user sign-up via hero section with valid data
        
        Given the user is on the GitHub homepage, When the user enters a valid unique email address in the hero section input and submits the form, Then the user should be navigated to the sign-up confirmation or next step page, and a success indicator should be present. This tests the primary critical user journey of account creation.
        """
        logger.info("Starting test: Verify successful user sign-up via hero section with valid data")
        
        # Test implementation
        try:
            # Initialize page object
            homepage = GitHubHomePage(self.page)
            
            # Execute test steps

            # Navigate to URL
            self.page.goto("https://github.com/")

            # Enter text: test_unique_12345@example.com
            self.page.locator("#hero_user_email").fill("test_unique_12345@example.com")

            # Click element
            self._safe_click("#hero_user_email + button, button[data-testid='hero-signup-button'], .hero-signup-button-css")

            
            # Test passed
            logger.info(f"Test passed: {method_name}")
            
        except Exception as e:
            self.screenshot_on_failure = True
            logger.error(f"Test failed: {e}")
            raise

    
    @pytest.mark.critical
    def test_successful_email_capture_via_hero_section_signup(self):
        """
        Successful Email Capture via Hero Section Signup
        
        Verifies the happy path for capturing a user's email address through the main hero section's call to action, which is a critical step towards user authentication. Includes basic validation, accessibility, and performance checks.
        """
        logger.info("Starting test: Successful Email Capture via Hero Section Signup")
        
        # Test implementation
        try:
            # Initialize page object
            homepage = GitHubHomePage(self.page)
            
            # Execute test steps

            # Assertion: 
            assert self.page.locator("{'primary': '#hero_user_email', 'alternatives': [{'type': 'css', 'value': 'input#hero_user_email'}, {'type': 'xpath', 'value': '/html/body/div/div[6]/main/react-app/div/div/div/section/div/div[5]/div/form/section/div/div/span/input'}]}").is_visible(), ""

            # Enter text: testuser@example.com
            self.page.locator("{'primary': '#hero_user_email', 'alternatives': [{'type': 'css', 'value': 'input#hero_user_email'}, {'type': 'xpath', 'value': '/html/body/div/div[6]/main/react-app/div/div/div/section/div/div[5]/div/form/section/div/div/span/input'}]}").fill("testuser@example.com")

            
            # Test passed
            logger.info(f"Test passed: {method_name}")
            
        except Exception as e:
            self.screenshot_on_failure = True
            logger.error(f"Test failed: {e}")
            raise

    
    def _wait_and_assert(self, selector: str, expected_text: str = None):
        """
        Wait for element and optionally assert text.
        
        Args:
            selector: Element selector
            expected_text: Expected text content
        """
        element = self.page.locator(selector)
        element.wait_for(state="visible", timeout=self.timeout)
        
        if expected_text:
            expect(element).to_contain_text(expected_text)
    
    def _safe_click(self, selector: str, retries: int = 3):
        """
        Click element with retry logic.
        
        Args:
            selector: Element selector
            retries: Number of retry attempts
        """
        for attempt in range(retries):
            try:
                element = self.page.locator(selector)
                element.wait_for(state="visible", timeout=self.timeout)
                element.click()
                return
            except Exception as e:
                if attempt == retries - 1:
                    raise
                logger.warning(f"Click attempt {attempt + 1} failed: {e}")
