"""
Test suite for validation strategy.
Generated by Advanced Test Code Generator
URL: https://github.com
"""

import pytest
from playwright.sync_api import Page, expect
import os
import logging
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv
import sys

# Add parent directory to path for imports
sys.path.append(str(Path(__file__).parent.parent))

# Import page objects
from pages.github_homepage import GitHubHomePage
from pages.base_page import BasePage

# Load environment variables
load_dotenv('.env.test')

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class TestValidation:
    """Test class for validation scenarios."""
    
    @pytest.fixture(autouse=True)
    def setup(self, page: Page):
        """
        Setup test environment.
        
        Args:
            page: Playwright page fixture
        """
        self.page = page
        self.base_url = os.getenv('BASE_URL', 'https://github.com')
        self.timeout = int(os.getenv('DEFAULT_TIMEOUT', '30000'))
        
        # Navigate to base URL
        self.page.goto(self.base_url)
        self.page.wait_for_load_state("networkidle")
        
        yield
        
        # Cleanup
        if hasattr(self, 'screenshot_on_failure') and self.screenshot_on_failure:
            self._take_failure_screenshot()
    
    def _take_failure_screenshot(self):
        """Take screenshot on test failure."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        screenshot_dir = Path("screenshots/failures")
        screenshot_dir.mkdir(parents=True, exist_ok=True)
        
        screenshot_path = screenshot_dir / f"{timestamp}_validation_failure.png"
        self.page.screenshot(path=str(screenshot_path))
        logger.info(f"Failure screenshot saved: {screenshot_path}")

    
    @pytest.mark.critical
    def test_tc001__validate_correct_email_format_input_in_hero(self):
        """
        TC001: Validate Correct Email Format Input in Hero Section Signup
        
        Verifies that the primary email input field in the hero section correctly accepts a standard, syntactically valid email address. This is crucial for user acquisition and ensuring data integrity from the first interaction point.
        """
        logger.info("Starting test: TC001: Validate Correct Email Format Input in Hero Section Signup")
        
        # Test implementation
        try:
            # Initialize page object
            homepage = GitHubHomePage(self.page)
            
            # Execute test steps

            
            # Test passed
            logger.info(f"Test passed: {method_name}")
            
        except Exception as e:
            self.screenshot_on_failure = True
            logger.error(f"Test failed: {e}")
            raise

    
    @pytest.mark.critical
    def test_tc002__validate_rejection_of_invalid_email_format_(self):
        """
        TC002: Validate Rejection of Invalid Email Format in Hero Section Signup
        
        Ensures the primary email input field in the hero section correctly identifies and rejects syntactically invalid email addresses, providing clear and actionable error feedback to the user. This tests the robustness of input validation.
        """
        logger.info("Starting test: TC002: Validate Rejection of Invalid Email Format in Hero Section Signup")
        
        # Test implementation
        try:
            # Initialize page object
            homepage = GitHubHomePage(self.page)
            
            # Execute test steps

            
            # Test passed
            logger.info(f"Test passed: {method_name}")
            
        except Exception as e:
            self.screenshot_on_failure = True
            logger.error(f"Test failed: {e}")
            raise

    
    def _wait_and_assert(self, selector: str, expected_text: str = None):
        """
        Wait for element and optionally assert text.
        
        Args:
            selector: Element selector
            expected_text: Expected text content
        """
        element = self.page.locator(selector)
        element.wait_for(state="visible", timeout=self.timeout)
        
        if expected_text:
            expect(element).to_contain_text(expected_text)
    
    def _safe_click(self, selector: str, retries: int = 3):
        """
        Click element with retry logic.
        
        Args:
            selector: Element selector
            retries: Number of retry attempts
        """
        for attempt in range(retries):
            try:
                element = self.page.locator(selector)
                element.wait_for(state="visible", timeout=self.timeout)
                element.click()
                return
            except Exception as e:
                if attempt == retries - 1:
                    raise
                logger.warning(f"Click attempt {attempt + 1} failed: {e}")
