"""
Test suite for security strategy.
Generated by Advanced Test Code Generator
URL: https://github.com
"""

import pytest
from playwright.sync_api import Page, expect
import os
import logging
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv
import sys

# Add parent directory to path for imports
sys.path.append(str(Path(__file__).parent.parent))

# Import page objects
from pages.github_homepage import GitHubHomePage
from pages.base_page import BasePage

# Load environment variables
load_dotenv('.env.test')

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class TestSecurity:
    """Test class for security scenarios."""
    
    @pytest.fixture(autouse=True)
    def setup(self, page: Page):
        """
        Setup test environment.
        
        Args:
            page: Playwright page fixture
        """
        self.page = page
        self.base_url = os.getenv('BASE_URL', 'https://github.com')
        self.timeout = int(os.getenv('DEFAULT_TIMEOUT', '30000'))
        
        # Navigate to base URL
        self.page.goto(self.base_url)
        self.page.wait_for_load_state("networkidle")
        
        yield
        
        # Cleanup
        if hasattr(self, 'screenshot_on_failure') and self.screenshot_on_failure:
            self._take_failure_screenshot()
    
    def _take_failure_screenshot(self):
        """Take screenshot on test failure."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        screenshot_dir = Path("screenshots/failures")
        screenshot_dir.mkdir(parents=True, exist_ok=True)
        
        screenshot_path = screenshot_dir / f"{timestamp}_security_failure.png"
        self.page.screenshot(path=str(screenshot_path))
        logger.info(f"Failure screenshot saved: {screenshot_path}")

    
    @pytest.mark.critical
    def test_prevent_sql_injection_via_user_email_input(self):
        """
        Prevent SQL Injection via User Email Input
        
        This test verifies that the system sanitizes user input in the email fields to prevent SQL injection attacks, ensuring data integrity and preventing unauthorized access or modification of the database. This targets the 'User Authentication' critical journey.
        """
        logger.info("Starting test: Prevent SQL Injection via User Email Input")
        
        # Test implementation
        try:
            # Initialize page object
            homepage = GitHubHomePage(self.page)
            
            # Execute test steps

            # Enter text: ' OR '1'='1
            self.page.locator("#hero_user_email").fill("' OR '1'='1")

            # Enter text: admin'; DROP TABLE users; --
            self.page.locator("#bottom_cta_section_user_email").fill("admin'; DROP TABLE users; --")

            # Click element
            self._safe_click("button.btn.btn-mktg.btn-primary.mb-3.js-navigation-target")

            
            # Test passed
            logger.info(f"Test passed: {method_name}")
            
        except Exception as e:
            self.screenshot_on_failure = True
            logger.error(f"Test failed: {e}")
            raise

    
    @pytest.mark.critical
    def test_input_sanitization_test__prevent_xss_and_sql_injec(self):
        """
        Input Sanitization Test: Prevent XSS and SQL Injection on Homepage Email Field
        
        Verifies that the primary email input field on the GitHub homepage correctly sanitizes malicious inputs, preventing Cross-Site Scripting (XSS) and SQL Injection (SQLi) attacks. This is crucial as this field might be used for initial sign-up or newsletter subscriptions, making it a target.
        """
        logger.info("Starting test: Input Sanitization Test: Prevent XSS and SQL Injection on Homepage Email Field")
        
        # Test implementation
        try:
            # Initialize page object
            homepage = GitHubHomePage(self.page)
            
            # Execute test steps

            # Assertion: The injected script tags are rendered as escaped HTML (e.g., '&lt;script&gt;...' or similar) and are NOT executed. No alert box appears. The input field should visually contain the escaped characters or be cleared/validated appropriately after attempting submission (if applicable).
            assert self.page.locator("{'primary': 'id=hero_user_email', 'fallback_css': '#hero_user_email', 'fallback_xpath': "//input[@id='hero_user_email']"}").is_visible(), "The injected script tags are rendered as escaped HTML (e.g., '&lt;script&gt;...' or similar) and are NOT executed. No alert box appears. The input field should visually contain the escaped characters or be cleared/validated appropriately after attempting submission (if applicable)."

            
            # Test passed
            logger.info(f"Test passed: {method_name}")
            
        except Exception as e:
            self.screenshot_on_failure = True
            logger.error(f"Test failed: {e}")
            raise

    
    def _wait_and_assert(self, selector: str, expected_text: str = None):
        """
        Wait for element and optionally assert text.
        
        Args:
            selector: Element selector
            expected_text: Expected text content
        """
        element = self.page.locator(selector)
        element.wait_for(state="visible", timeout=self.timeout)
        
        if expected_text:
            expect(element).to_contain_text(expected_text)
    
    def _safe_click(self, selector: str, retries: int = 3):
        """
        Click element with retry logic.
        
        Args:
            selector: Element selector
            retries: Number of retry attempts
        """
        for attempt in range(retries):
            try:
                element = self.page.locator(selector)
                element.wait_for(state="visible", timeout=self.timeout)
                element.click()
                return
            except Exception as e:
                if attempt == retries - 1:
                    raise
                logger.warning(f"Click attempt {attempt + 1} failed: {e}")
