version: '3.8'

services:
  pyspark:
    build:
      context: .
      dockerfile: Dockerfile.pyspark  # Now using PySpark 3.3.2
    container_name: pyspark-app
    ports:
      - "4040:4040"  # Spark UI
      - "8080:8080"  # Spark Master UI
      - "8081:8081"  # Spark Worker UI
      - "7077:7077"  # Spark Master
      - "8888:8888"  # Jupyter Lab
    volumes:
      - .:/workspace
      - pyspark_data:/data
    environment:
      - SPARK_MASTER_HOST=localhost
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_CORES=2
    command: tail -f /dev/null
    
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.pyspark  # Now using PySpark 3.3.2
    container_name: jupyter-pyspark
    ports:
      - "8889:8888"  # Alternative Jupyter port
    volumes:
      - .:/workspace
      - pyspark_data:/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''

volumes:
  pyspark_data:
